version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# On bascule officiellement sur Sphinx en lui donnant le chemin de votre conf.py
sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt